### PR TITLE
Fix search bar at top of page

### PR DESCRIPTION
**Pull request by cshinn**
Fixes search bar to the top of the page, also addresses small visual bug in search dropdown. Width: inherit does not work in this case because of the  `<catalog-search>` item

screen shot 2017-04-07 at 2 56 13 pm 2

### CODE REVIEW

**Comment by rhamilto** [comment]
@cshinn, .landing-search-area needs a background color and a z-index: @zindex-navbar-fixed to avoid the scrolling contents changing behind it/over it.

screen shot 2017-04-07 at 1 34 30 pm

**Comment by cshinn** [comment]
@rhamilto added the z-index, but I'm not sure how to best deal with the background image. Should I add a solid color for now? Should probably get visuals input

**Comment by rhamilto** [comment]
@cshinn, you're going to need to duplicate the bg-color and image from #96 in that area (they'll overlap one another).

**Comment by cshinn** [comment]
Search bar area now uses background image to cover page content

**Pull request merged**
