### PR TITLE
Add append-to-body to ui-selects within modals

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Review by jwforres — APPROVED** [review]

**Review by spadgett — APPROVED** [review]

**Comment by spadgett** [comment]
We should bump common as part of this pr

**Review by rhamilto — COMMENTED** [review]
LGTM pending Travis.

**Comment by rhamilto** [comment]
Travis failure fixed by https://github.com/sg00dwin/origin-web-catalog/pull/1

**Comment by sg00dwin** [comment]
/hold 
will go in next release

**Pull request closed without merging**
