### PR TITLE
Fix bug where pficons do not display

### PR DESCRIPTION
**Pull request by rhamilto**
Requires https://github.com/openshift/origin-web-common/pull/270
Partial fix for https://github.com/openshift/origin/issues/17745

### CODE REVIEW

**Comment by spadgett** [comment]
@rhamilto See my comment in the other PR... I think we need a common filter for this since we use it in so many places (at least 7?)

**Comment by rhamilto** [comment]
Now utilizes normalizeIconClass filter from origin-web-common#v3.9.0-alpha.3.

**Comment by rhamilto** [comment]
@benjaminapetersen, mind giving this a review?

**Comment by benjaminapetersen** [comment]
@rhamilto yup, pulling it down to take a look

**Pull request merged**
