### PR TITLE
Look for provider display name annotation on image streams

### PR DESCRIPTION
**Pull request by spadgett**
Waiting for consensus on the name in https://github.com/openshift/origin/issues/16755

@sspeiche

### CODE REVIEW

**Comment by spadgett** [comment]
Annotation is `openshift.io/provider-display-name` for both templates and image streams.

https://github.com/openshift/origin/issues/16755#issuecomment-337478454

Removing WIP from the PR

**Comment by spadgett** [comment]
See also

https://github.com/openshift/origin/pull/16925
https://github.com/openshift/origin/pull/16899

**Comment by rhamilto** [comment]
@spadgett, don't forget to update the create-from-builder template and controller.  #485 ended up not including the necessary updates.

**Comment by jwforres** [comment]
Will wait to review till @rhamilto 's comment is addressed

**Comment by spadgett** [comment]
Thanks @rhamilto I updated the dialog, too.

**Comment by jwforres** [comment]
LGTM but waiting on the origin PR to get merged, also travis is failing

**Comment by spadgett** [comment]
> also travis is failing

The new vendor I added to the mock image stream was causing the tests to fail. Just pushed an update.

**Comment by spadgett** [comment]
Rebased

**Comment by spadgett** [comment]
Upstream change has merged

**Pull request merged**
