### PR TITLE
Tighten versions of @types and typescript dependencies

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes current build issue.

### CODE REVIEW

**Comment by jwforres** [comment]
just waiting for travis to pass

**Comment by jeff-phillips-18** [comment]
Travis failing on verify-dist, tightening up more (use specific releases) to attempt to resolve the issue.

**Comment by jeff-phillips-18** [comment]
Removed last change. 

I cannot determine why verify-dist is failing. I have done clean-deps and install-deps and rebuilt and I get no changes.

**Comment by jeff-phillips-18** [comment]
Found the issue. Version of uglify-js needed to be tightened as well.

**Comment by jwforres** [comment]
thanks for tracking that down

**Pull request merged**
