### PR TITLE
Hide items with a 'hidden' tag

### PR DESCRIPTION
**Pull request by spadgett**
cc @sspeiche

### CODE REVIEW

**Comment by spadgett** [comment]
Hm, not sure what is wrong in Travis:

```
10 10 2017 13:58:16.953:INFO [Firefox 49.0.0 (Linux 0.0.0)]: Connected on socket MN95d2HHaPVwQTsnAAAA with id 80085566
Firefox 49.0.0 (Linux 0.0.0) ERROR
  TypeError: __webpack_require__.i(...) is not a function
  at test/test-bundle.ts:9
Firefox 49.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (2.908 secs / 0 secs)
```

**Comment by dtaylor113** [comment]
@spadgett, just rebased origin-web-catalog, hack clean & install deps, npm test.  Passed 40 out of 40.  Looks like Travis failed with the 'executed 0 of 0' issue which we initially fixed by using FireFox v49.  Not sure what's wrong with Travis.

**Comment by spadgett** [comment]
Closing and reopening to force Travis to retest.

**Comment by dtaylor113** [comment]
Just set
```
node --version
v4.8.3
npm --version
2.15.11
```
Now I'm getting the unit test failures seen in Travis.
cc @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
Can we update the npm version being used by travis?

**Comment by dtaylor113** [comment]
@spadgett, why is Travis using such an old version of node?   Can we update it to use node v5?

**Comment by spadgett** [comment]
Trying node 6 in #482

**Comment by spadgett** [comment]
Removed the provider annotation from this PR since there's still some debate on the name. I'll open a follow up for that.

**Comment by spadgett** [comment]
Opened #487 for provider display name

@jeff-phillips-18 PTAL

**Pull request merged**
