### PR TITLE
Change subcategory background color

### PR DESCRIPTION
**Pull request by cshinn**
An alternate coloration of the subcategory background

screen shot 2017-04-13 at 9 26 49 am

screen shot 2017-04-13 at 9 26 54 am

screen shot 2017-04-13 at 9 25 57 am

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Might look better if there was some margin around the catalog items panel to show a touch of the background image.

**Comment by rhamilto** [comment]
To my eye, the primary nav is getting lost now.  Reducing the opacity on the h1 (.5) and the primary nav (.8) and increasing it on the tab bg (.95) improves things.

screen shot 2017-04-13 at 10 45 47 am

**Comment by serenamarie125** [comment]
@rhamilto imo that brings in too many lines/stripes, I'd prefer the original.  I particularly like the fact that you can see the image in the area next to the subcategories.

**Comment by spadgett** [comment]
This isn't a new problem, but it's odd to me that there's a max height and scrollbar here when there's a lot of space below. Changing the color to white makes it feel even more like I should be able to use the whole space.

screen shot 2017-04-13 at 12 08 55 pm

**Comment by beanh66** [comment]
@spadgett I agree with you it is a little weird since we have the space. @rhamilto I agree with @serenamarie125 on the stripes, adding too many horizontal lines may be distracting.

**Comment by jeff-phillips-18** [comment]
A bit more space looks good to me:

image

**Comment by serenamarie125** [comment]
I think this already got merged, but @jeff-phillips-18 we should take a look at that with the blue background and see if it looks good when resized.  I definitely like the direction.

**Comment by beanh66** [comment]
@jeff-phillips-18 @serenamarie125 I agree, this looks great with the margins.

**Pull request merged**
