### PR TITLE
Removing config.local.js from repo.

### PR DESCRIPTION
**Pull request by dtaylor113**
Addresses #8 "config.local.js should not be tracked"

### CODE REVIEW

**Comment by spadgett** [comment]
It looked like config.local.js is required in various places? We should only use it if it exists and fall back to config.js.

**Comment by jeff-phillips-18** [comment]
This needs to come along with using config.js if config.local.js does not exist.

**Comment by dtaylor113** [comment]
config.js is in the repo?  Not sure what I need to udpate? 'npm run build' works on my computer, not sure why Travis is failing.

**Comment by spadgett** [comment]
The idea is that config.local.js is optional, but we're requiring it in several places:

https://github.com/openshift/origin-web-catalog/search?utf8=%E2%9C%93&q=config.local.js

**Comment by dtaylor113** [comment]
ah, ok, working on it

**Comment by dtaylor113** [comment]
Hi @spadgett & @jeff-phillips-18 , this addresses config.local.js .vs config.js.  It also fixes Travis Unit Test timeouts.

**Pull request merged**
