### PR TITLE
Use `inline-source-map` for development

### PR DESCRIPTION
**Pull request by spadgett**
cc @jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
@jeff-phillips-18 @dtaylor113 Do you know why travis is failing on dist? I wouldn't expect webpack.dev.js to affect that.

**Comment by dtaylor113** [comment]
Umm..not sure, did you rebase to latest and do 'npm run build'?  I wouldn't think webpack.dev.js would involve the files in /dist

**Comment by jeff-phillips-18** [comment]
@spadgett I'm guessing npm/bower dependencies are not up to date.

**Comment by spadgett** [comment]
`npm run build` has different output for `dist/origin-web-catalogs.js` after the `webpack.dev.js` changes

**Comment by spadgett** [comment]
Rebased. No dist/ changes after #26 (thanks @jeff-phillips-18)

**Pull request merged**
