### PR TITLE
Fixing bug where wizard steps indicator was too narrow in IE11

### PR DESCRIPTION
**Pull request by rhamilto**
Before:

screen shot 2017-05-11 at 4 40 55 pm

After:

screen shot 2017-05-11 at 4 28 31 pm

### CODE REVIEW

**Comment by serenamarie125** [comment]
@jeff-phillips-18 did you create a PF issue?

**Comment by rhamilto** [comment]
> LGTM, we should file an issue to get this fixed in patternfly.

This was an [intentional implementation decision in PatternFly](https://github.com/patternfly/patternfly/blame/master/src/less/wizard.less#L115-L117).  Paging @priley86

**Comment by priley86** [comment]
@rhamilto yes, I still prefer autoprefixer and think it saves us a ton more effort. 

in this case, I have opted to ease the stylint rules to ignore `"consecutive-duplicates-with-different-values"`. This allows us to still add `display: flex` after `display: inline-block` for ie11 (which does not support `@support` blocks like other browsers), and let autoprefixer take care of the prefixing for ie10/11. will this fix work for you?
https://github.com/patternfly/patternfly/pull/645

Out of curiosity, what minimum IE support does your app have these days? Microsoft has ended support for all IE versions except IE11.  It'd be nice to rid ourselves of these IE10 prefixes...and of course I can't wait for the day until we can just say "flex" and use BS4...
https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

**Comment by rhamilto** [comment]
> in this case, I have opted to ease the stylint rules to ignore "consecutive-duplicates-with-different-values". This allows us to still add display: flex after display: inline-block for ie11 (which does not support @support blocks like other browsers), and let autoprefixer take care of the prefixing for ie10/11. will this fix work for you?
patternfly/patternfly#645

It will.  Thanks, @priley86.

> Out of curiosity, what minimum IE support does your app have these days? 

We only support 11.

**Pull request merged**
