### PR TITLE
Let users toggle expansion of subcategories

### PR DESCRIPTION
**Pull request by spadgett**
@jeff-phillips-18 @dtaylor113 Opinion on this change? My understanding is that you should be able to toggle the subcategories open and closed. This also changes it not to expand the first by default.

cc @jwforres

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM!  Thanks

**Comment by dtaylor113** [comment]
Hi, I believe I have fixed the failing Travis unit tests in PR #9.  Once that PR is merged, a rebase should resolve this Travis Build issue.  -thanks

**Comment by jeff-phillips-18** [comment]
Looks like unit tests are failing due to the change

**Comment by jeff-phillips-18** [comment]
Build is passing and reporting correctly now.

**Pull request merged**
