### PR TITLE
Adopt new service catalog resource names

### PR DESCRIPTION
**Pull request by spadgett**
https://trello.com/c/y1lbFrbp

Instance -> ServiceInstance
Binding -> ServiceInstanceCredential

Bump origin-web-common to 0.0.56

Requires:

https://github.com/openshift/origin-web-common/pull/182

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
mockData.service.ts references 'instances' to get mock service instances:
https://github.com/openshift/origin-web-catalog/blob/master/app/mockServices/mockData.service.ts#L233

**Comment by jeff-phillips-18** [comment]
Other instances:
https://github.com/openshift/origin-web-catalog/blob/master/src/components/create-from-builder/create-from-builder.controller.ts#L111
https://github.com/openshift/origin-web-catalog/blob/master/src/components/create-from-builder/create-from-builder.controller.ts#L296
https://github.com/openshift/origin-web-catalog/blob/master/src/components/order-service/order-service.controller.ts#L258

**Comment by spadgett** [comment]
@jeff-phillips-18 Thanks for catching that. I think I had a typo in my search for `instances`

**Comment by spadgett** [comment]
@jmontleon FYI, this PR is updated.

Building with @jpeeler's changes now to test

**Comment by dtaylor113** [comment]
Cannot find any instances of:
```
resource: 'bindings'
case 'bindings'
kind: "bindings"
resource: "instances"
case 'instances'
kind: "Instance"
```
Searched in /app, /src and /test using both single and double quotes.

**Comment by spadgett** [comment]
Bumped origin-web-common to 0.0.56

Tests running cleanly locally:

> Safari 10.1.2 (Mac OS X 10.12.6): Executed 39 of 39 SUCCESS (5.089 secs / 2.847 secs)

**Comment by benjaminapetersen** [comment]
The failure in travis is weird:

```bash
1 CURSOR_BITSs still allocated at reset
TOTAL: 0 objects, 0 bytes, 0 allocs
[dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
npm ERR! Test failed.  See above for more details.
The command "hack/test-headless.sh test" exited with 1.
```

**Comment by spadgett** [comment]
Yeah, it's the same problem in #428. Tests aren't running in Travis.

**Comment by benjaminapetersen** [comment]
Ok.  More test fun :)

**Pull request merged**
