### PR TITLE
Update to use v1.1.0 of openshift-logos-icon with new Apache and Infinispan logos

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM although travis isnt happy

**Comment by rhamilto** [comment]
I forgot to publish to NPM. Will do so in the AM.

**Comment by rhamilto** [comment]
[test]

**Comment by rhamilto** [comment]
v1.1.0 of openshift-logos-icon is coming, so let me update this PR to that version once the release is complete.

**Comment by rhamilto** [comment]
> v1.1.0 of openshift-logos-icon is coming, so let me update this PR to that version once the release is complete.

Done.  Ready for merge once the stream opens.

**Pull request merged**
