### PR TITLE
Optionally support stacked forms in select-project component

### PR DESCRIPTION
**Pull request by spadgett**
This will let us use the control in some web console pages that have stacked forms rather than horizontal forms. Also add the required style to the label.

Stacked form:

screen shot 2017-05-02 at 11 37 59 am

Horizontal form (default):
 
screen shot 2017-05-02 at 11 57 07 am

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres @dtaylor113 I added a flag to only default a project if one is not passed in. This doesn't change the behavior when used in the catalog (still defaults to most recent project there).

**Comment by spadgett** [comment]
Squash and fixed dist

**Comment by dtaylor113** [comment]
@spadgett unit test failures?

**Comment by spadgett** [comment]
@dtaylor113 Yeah, looking at it, although hard to debug because I can't run the tests.

**Comment by dtaylor113** [comment]
@spadgett Why can't you run the tests?  Does `npm tests` not work for you?

**Comment by spadgett** [comment]
@dtaylor113 It has never worked for me.

**Comment by spadgett** [comment]
This was not ready to merge, still debugging test failures. Going to revert since the commit that was merged had a bug.

**Pull request merged**
