### PR TITLE
Change "Vendor" filter to "Publisher"

### LINKED ISSUE #411: Is "Vendor" the right label for the faceted filter?
I am wondering if "Publisher" or "Provider" isn't more accurate. The metadata field is `providerDisplayName`. It looks odd to me that "Red Hat, Inc." is the vendor for ".NET"

openshift web console 2017-08-31 14-56-55

@sspeiche @serenamarie125 @pmorie

### PR DESCRIPTION
**Pull request by spadgett**
Closes #411

### CODE REVIEW

**Comment by spadgett** [comment]
> Firefox 55.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (0.079 secs / 0 secs)

Hm, looks like a test flak in Travis. Going to close and reopen the pull to kick the tests.

**Comment by spadgett** [comment]
@jeff-phillips-18 @dtaylor113 For some reason, tests aren't running in Travis.

**Comment by dtaylor113** [comment]
> @jeff-phillips-18 @dtaylor113 For some reason, tests aren't running in Travis.

Travis is now using Firefox 55.0.0 which has issues running the unit tests.

**Comment by spadgett** [comment]
@dtaylor113 Thanks, testing if `latest-esr` works for Travis in #432

**Comment by spadgett** [comment]
Closing and reopening to kick the Travis tests

**Pull request merged**
