### PR TITLE
Change subcategory styling

### PR DESCRIPTION
**Pull request by rhamilto**
Supports https://github.com/openshift/origin-web-console/issues/2454

Note:  @jennyhaines requested some tweaks that make this implementation different from [her mock](https://github.com/openshift/origin-web-console/issues/2454#issuecomment-342304860).

screen shot 2017-11-07 at 2 15 09 pm
screen shot 2017-11-07 at 2 15 25 pm
screen shot 2017-11-07 at 2 15 42 pm

as seen in the console:
screen shot 2017-11-07 at 2 15 57 pm

cc: @openshift/team-ux-review

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold
found a bug

**Comment by spadgett** [comment]
/hold

for @jwforres review

**Comment by jennyhaines** [comment]
@rhamilto - Why are some of the subcategory icons black, and others full color? I'd recommend the full color.

**Comment by spadgett** [comment]
@jennyhaines They'll be in full color. Some of the mock test data we use is only black and white.

**Comment by jwforres** [comment]
My only concern is the thin blue bar at the top of the active tile. Its really hard to distinguish that bar from the background. What ends up happening is it makes the active tile look like it is not aligned correctly with the other tiles.  I've walked by @spadgett and @rhamilto 's screens a few times and every time it bothers me that it looks like it is not aligned.

It's not as bad looking at the zoomed in screenshots, but on an actual screen it just looks off.

**Comment by jennyhaines** [comment]
@rhamilto  - I'm personally fine reverting back to having the blue bar down one pixel so it appears within the white card, rather than hovering 1px above. I know that you said it could look like that tile is receding, but I see what @jwforres is saying about it appearing misaligned, and visually that might be a more important problem to fix.

**Comment by serenamarie125** [comment]
@jennyhaines @rhamilto what about tightening up margin above/below filter?  Wondering if that will also save a bit of space?  Unsure if it would look crammed though.  Thoughts?

**Comment by serenamarie125** [comment]
@rhamilto were you able to implement the hover suggestion as well?

**Comment by jennyhaines** [comment]
@serenamarie125 - the space is tightened up from the original implementation. It's now 15px above instead of (I think) 27px. I think any less padding, and it would look a little tood snug (I tried it out as small as 10px, and that didn't work.)

**Comment by serenamarie125** [comment]
ok great thank @jennyhaines !

**Comment by rhamilto** [comment]
> @rhamilto were you able to implement the hover suggestion as well?

Yep.  Here Java is hovered:

screen shot 2017-11-07 at 1 47 52 pm

**Comment by jwforres** [comment]
we fiddled with the blue bar on @rhamilto 's screen and nothing really looks right on an actual monitor in context of the whole page, @smarterclayton @spadgett and I all agreed to nix the blue bar on the active state. Its pretty obvious what is active vs what is hovered based on which tile is connected.

**Comment by jennyhaines** [comment]
@jwforres Okay, that works especially since this design may only be used for this upcoming release. The slight 2px top corners of the unselected state tiles help to differentiate them even more.

**Pull request merged**
