### PR TITLE
Refactor services-view styles for within a project

### PR DESCRIPTION
**Pull request by rhamilto**
Supports https://github.com/openshift/origin-web-console/issues/2592

localhost_9000_dev-console_project_myproject_catalog ipad pro
localhost_9000_dev-console_project_myproject_catalog iphone 8 plus
localhost_9000_dev-console_project_myproject_catalog iphone 8 plus 1
localhost_9000_dev-console_project_myproject_catalog iphone 8 plus 2

cc: @jennyhaines

### CODE REVIEW

**Comment by jennyhaines** [comment]
@rhamilto - I think this looks great, except I just noticed that the "< Back" link on the 3rd and 4th image don't align to anything. I would think that it would be aligned directly under the words "My Project", above it. I'm seeing the same thing on the second image with "Select an item...". I would think that would be aligned under "My Project".

**Comment by rhamilto** [comment]
> @rhamilto - I think this looks great, except I just noticed that the "< Back" link on the 3rd and 4th image don't align to anything. I would think that it would be aligned directly under the words "My Project", above it. I'm seeing the same thing on the second image with "Select an item...". I would think that would be aligned under "My Project".

Good eye, @jennyhaines!  I wrestled with that and couldn't find a good option.  I'll make your proposed change and update screenshots.

**Comment by sg00dwin** [comment]
@rhamilto to get rid of the transition position movement adjust these rules 

```
.services-inner-container {
  position: relative;
}
.services-view .services-view-container .services-no-sub-categories.ng-enter, .services-view .services-view-container .services-no-sub-categories.ng-enter-prepare, .services-view .services-view-container .services-sub-categories.ng-enter, .services-view .services-view-container .services-sub-categories.ng-enter-prepare {
  top: 0;
}

.services-view .services-no-sub-categories {
    // make top padding 15px to match => .services-view .services-no-sub-categories 
}

```

**Comment by rhamilto** [comment]
Now incorporates fixes from @sg00dwin.  @sg00dwin, mind taking another look?

**Comment by rhamilto** [comment]
@sg00dwin is working on an animation fix, but I'm gonna merge this now and handle the animation fix as a follow-on.

**Pull request merged**
