### PR TITLE
Fix svg display bug

### LINKED ISSUE #180: Font Icons are not showing up in SaaS area in some versions of Chrome & Firefox
Looks like newer versions of Chrome & Firefox cause issues with the font icons.

Here is Chrome:
screen shot 2017-04-27 at 12 01 30 pm

Here is Safari running the same build:
screen shot 2017-04-27 at 12 01 43 pm

### PR DESCRIPTION
**Pull request by cshinn**
SVGs now display properly in most recent version of Chrome and Firefox

Closes #180

### CODE REVIEW

**Comment by rhamilto** [comment]
[test]

**Comment by cshinn** [comment]
@rhamilto I've just noticed that this causes some weird effects in IE11. SVGs appear slightly flattened. I think it's a flexbug

**Comment by rhamilto** [comment]
> @rhamilto I've just noticed that this causes some weird effects in IE11. SVGs appear slightly flattened. I think it's a flexbug

@cshinn for today, I think it's ok to roll with the IE11 bug.  We'll want to circle back to that in the near future.  Please open an issue for it?  Ideally we'd be following the advice in https://css-tricks.com/scale-svg/ and not using width and height attributes to scale the SVGs...

**Comment by cshinn** [comment]
This could theoretically be any kind of image file though, couldn't it?

**Comment by rhamilto** [comment]
> This could theoretically be any kind of image file though, couldn't it?

Good point.  So we'll need to figure out the bug (but not necessarily now since this seems to resolve the immediate issue).  I'm in the process of staging the data as pictured so I can better see what's happening.

**Comment by cshinn** [comment]
@rhamilto just an FYI, This fix works on the most recent chrome and ff in fedora as well as on edge. Looks like the only one that still looks weird is IE 11, which looked fine before the fix.

**Comment by dtaylor113** [comment]
Hi @cshinn, after you rebase that Travis error should go away :-)

**Comment by rhamilto** [comment]
Closing in favor in #187

**Pull request closed without merging**
