### PR TITLE
Update Middleware subcategories

### PR DESCRIPTION
**Pull request by spadgett**
Recommended subcategories for Middleware templates from @sspeiche 

openshift catalog components 2017-09-19 13-52-57

@rhamilto I might need some help with styling tiles that have longer labels.

@serenamarie125 FYI

### CODE REVIEW

**Comment by spadgett** [comment]
@beanh66

**Comment by beanh66** [comment]
Thanks @spadgett, Jenny has a story that we are tracking in [Jira](https://patternfly.atlassian.net/projects/OSUX/issues/OSUX-168) for the Middleware subcategory icon creation :+1:

**Comment by spadgett** [comment]
I'll pulled in some style changes from @rhamilto for the longer labels.

screen shot 2017-10-05 at 1 10 01 pm

**Comment by spadgett** [comment]
Added dist

**Comment by beanh66** [comment]
@spadgett Awesome, I think the subcategories look way better with all the tiles being the same width 👍

**Pull request merged**
