### PR TITLE
Bump origin-web-common to 0.0.8

### PR DESCRIPTION
**Pull request by spadgett**

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Need to bump the version in package.json as well.

It is in bower.json so that the dependency is known by those installing with bower but in order to use it in catalogs and not include it in vendor.js it has to be used from the npm install.

**Comment by spadgett** [comment]
Thanks, I updated package.json now too, but I don't see any changes in the dist folder after reinstalling / rebuilding. Did I miss something?

**Comment by jeff-phillips-18** [comment]
No, that change shouldn't effect it.

**Comment by spadgett** [comment]
@jeff-phillips-18 Spoke with @jwforres and she was going to update the panel styles for the large panel. Then I think we should cut a release with everything and update both origin-web-catalog and origin-web-common in the console repo at the same time to avoid bower conflicts.

**Pull request merged**
