### PR TITLE
Move angular-ui-router to dev dependency and bump to latest 1.0.X

### PR DESCRIPTION
**Pull request by TheRealJon**
Fixes issue #654 

# Changes
- Fix angular-ui-router deprecation warning by moving to `@uirouter/angularjs`
- Move ui router to dev dependencies
- Update version constraint to '^1.0.0'

### CODE REVIEW

**Comment by spadgett** [comment]
@TheRealJon were you able to verify the sample app still worked?

**Comment by TheRealJon** [comment]
Yes, sample app still works with angular-ui-router v1.0.3

**Comment by spadgett** [comment]
I'd expect a package-lock.json change.

**Comment by TheRealJon** [comment]
I did just notice that there is a deprecation warning for that package. I might as well see if I can fix that too.

**Review by dtaylor113 — APPROVED** [review]
assuming we get the package-lock.json file updated.

**Review by spadgett — APPROVED** [review]

**Pull request merged**
