### PR TITLE
Show search 'View All' regardless of results count

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
also removed the auto-select of the first item and autocomplete for the input. First item shows selected on a down arrow key.

Fixes https://github.com/openshift/origin-web-console/issues/1758

@openshift/team-ux-review 

search-typeahead

### CODE REVIEW

**Comment by jwforres** [comment]
im guess its saying "view all 1 results" when there is only 1 since no special logic was added to handle 1 result

**Comment by jeff-phillips-18** [comment]
@jwforres correct. Not sure what the appropriate wording would be there. "View all 1 result" doesn't make much sense either.

**Comment by jwforres** [comment]
Yeah it sounds weird either way :)

**Comment by ncameronbritt** [comment]
Hopefully that one result is the thing they're looking for and the won't care what it says :-)

**Comment by jeff-phillips-18** [comment]
For one result:

image


For no results:

image

**Comment by jwforres** [comment]
works for me  @openshift/team-ux-review do yall have any other feedback before we merge it?

**Comment by ncameronbritt** [comment]
Works for me.

**Pull request merged**
