### PR TITLE
Fix to require 1.5 based version of angular types

### PR DESCRIPTION
**Pull request by jeff-phillips-18**

### CODE REVIEW

**Comment by jwforres** [comment]
curious why this is necessary?

**Comment by rhamilto** [comment]
@jeff-phillips-18, this fixes `npm run build` for me, but `npm run start` throws the following errors:

 npm run start

> origin-web-catalog@0.0.25 start /Users/rhamilto/Git/origin-web-catalog
> webpack-dev-server --config config/webpack.dev.js --history-api-fallback --inline --progress --open

 10% building modules 1/1 modules 0 active                                         
Project is running at http://localhost:9001/
webpack output is served from http://localhost:9001/
Content not from webpack is served from ./src
404s will fallback to /index.html
 10% building modules 2/3 modules 1 active ...lto/Git/origin-web-catalog/app/app.tswebpack: wait until bundle finished: /
 10% building modules 2/5 modules 3 active .../webpack-dev-server/client/overlay.jsts-loader: Using typescript@2.3.4 and /Users/rhamilto/Git/origin-web-catalog/tsconfig.json
chunk    {0} catalogs-app.js, catalogs-app.css, catalogs-app.css (catalogs-app) 5.27 MB {1} [initial] [rendered]
chunk    {1} vendor-bundle.js (vendor-bundle) 0 bytes [entry] [rendered]

ERROR in ./~/origin-web-common/dist/origin-web-common-ui.js
Module not found: Error: Can't resolve 'messenger/build/js/messenger' in '/Users/rhamilto/Git/origin-web-catalog/node_modules/origin-web-common/dist'
 @ ./~/origin-web-common/dist/origin-web-common-ui.js 2:16-55
 @ ./app/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:9001 ./app/app.ts

ERROR in ./~/origin-web-common/dist/origin-web-common.js
Module not found: Error: Can't resolve 'messenger/build/js/messenger' in '/Users/rhamilto/Git/origin-web-catalog/node_modules/origin-web-common/dist'
 @ ./~/origin-web-common/dist/origin-web-common.js 2:16-55
 @ ./app/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:9001 ./app/app.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 569 bytes [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 502 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 500 kB [entry] [rendered]
webpack: Failed to compile.

**Comment by jeff-phillips-18** [comment]
@jwforres The 1.6 version of Angular requires JQuery 3. Using ^ was pulling a 1.6.x version of the @types/angular which pulled in jqlite which re-defines some of the JQuery 2 settings (such as cssPropertySetter).  We need to keep at angular 1.5 versions.

**Comment by jeff-phillips-18** [comment]
@rhamilto Looking into that problem now. I can't see where messenger is being used, it is not set as a bower dependency anywhere. If I bower install it all is well, trying to figure out where it is being used.

**Comment by jwforres** [comment]
Yep nevermind, I was reading the ^ like it was the # for some reason :-)

**Comment by jwforres** [comment]
messenger used to be used in common by the old notification service but that dependency was removed when we switched to toasts

**Comment by jeff-phillips-18** [comment]
@jwforres Yup, and we had an import-loader in webpack for messenger. Removing that loader resolves the issue.

**Comment by jeff-phillips-18** [comment]
Added commit to fix webpack issue.

**Pull request merged**
